# This pipeline is triggered on pushes to the 'pipeline' branch.
trigger:
- pipeline

# Use a Microsoft-hosted agent running Ubuntu.
pool:
  vmImage: 'ubuntu-latest'

# Define variables.
variables:
- group: GitHub-Credentials
- name: imageRepository
  value: 'mynode-app' # The name of the image
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
# The full path for the image in GitHub Container Registry
- name: imageName
  value: 'ghcr.io/$(GITHUB_USER)/$(imageRepository)'

# Pipelines are organized into stages. We have one stage: Build.
stages:
- stage: Build
  displayName: 'Build and Push to GHCR'
  jobs:
  - job: Build
    displayName: 'Build and Push Docker image'
    steps:
    # Step 1: Login to GitHub Container Registry
    - task: Docker@2
      displayName: 'Login to ghcr.io'
      inputs:
        command: 'login'
        containerRegistry: 'Other'
        dockerRegistryEndpoint: 'GitHubContainerRegistry'
        dockerRegistryServiceConnection: |
          {
            "username": "$(GITHUB_USER)",
            "password": "$(GITHUB_PAT)",
            "registry": "https://ghcr.io"
          }

    # Step 2: Build and Push the Docker image to ghcr.io
    - task: Docker@2
      displayName: 'Build and Push image to ghcr.io'
      inputs:
        command: 'buildAndPush'
        # The repository name MUST be the full path
        repository: '$(imageName)'
        dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest